import {
  StudentProfile,
  UserSkill,
  AssessmentQuestion,
  Opportunity,
  Application,
} from '@/lib/types';

// Default Student Profile (Dynamic baseline for demonstration)
// Default Student Profile (Dynamic branch-neutral baseline for universal academia -> industry mapping)
export const INITIAL_STUDENT_PROFILE: StudentProfile = {
  id: 'sp-aditi-001',
  user_id: 'usr-aditi-001',
  profile_id: 'prof-aditi-001',
  full_name: 'Aditi Sharma',
  institution_id: 'inst-01',
  institution_name: 'RUAS Institute of Technology, Bengaluru',
  academic_stream: 'Computer Science & Engineering',
  department: 'Computer Science & Engineering',
  degree: 'Bachelor of Technology (B.Tech)',
  specialization: 'Software Engineering & Intelligent Systems',
  course: 'Bachelor of Technology (B.Tech)',
  year: 4,
  career_goal: 'Software Engineer',
  target_role: 'Software Engineer',
  preferred_roles: ['Software Engineer', 'Full Stack Developer', 'Data Analyst'],
  preferred_industry: 'Technology & Software Development',
  preferred_locations: ['Bengaluru', 'New Delhi', 'Mumbai', 'Remote'],
  preferred_work_type: 'Hybrid',
  availability: 'Immediate (Internship / Final Year)',
  overall_readiness_score: 82,
  bio: 'Final year Computer Science student specializing in scalable software design, web technologies, and database optimization.',
  resume_url: '/resumes/aditi_sharma_cv.pdf',
  public_slug: 'aditi-sharma',
  created_at: '2026-01-15T10:00:00Z',
  interests: ['Software Engineering', 'System Architecture', 'Web Development', 'Data Analysis'],
  projects: [
    {
      title: 'Distributed Microservices & API Gateway',
      description: 'Engineered a high-performance RESTful API gateway with automated request caching and OAuth2 authentication.',
      skills_used: ['JavaScript', 'Node.js', 'React', 'SQL', 'System Architecture'],
    },
  ],
  certifications: [
    { name: 'AWS Certified Cloud Practitioner', issuer: 'Amazon Web Services', year: 2025 },
  ],
  experience: [
    {
      title: 'Full Stack Engineering Intern',
      organization: 'TechOps Solutions',
      duration: '6 Months',
      description: 'Assisted in building web interfaces, optimizing SQL database queries, and integrating CI/CD deployment pipelines.',
    },
  ],
};

// Initial User Skills
export const INITIAL_USER_SKILLS: UserSkill[] = [
  {
    id: 'us-01',
    student_id: 'sp-aditi-001',
    skill_id: 's-cs-01',
    skill_name: 'JavaScript',
    category: 'Programming Languages',
    proficiency_score: 85,
    verification_status: 'INSTITUTION_VERIFIED',
    verified_by: 'RUAS Computer Science Dept',
    confidence_score: 90,
    updated_at: '2026-02-10T14:30:00Z',
  },
  {
    id: 'us-02',
    student_id: 'sp-aditi-001',
    skill_id: 's-cs-02',
    skill_name: 'React',
    category: 'Frontend Development',
    proficiency_score: 78,
    verification_status: 'INSTITUTION_VERIFIED',
    verified_by: 'RUAS Computer Science Dept',
    confidence_score: 85,
    updated_at: '2026-02-12T11:00:00Z',
  },
  {
    id: 'us-03',
    student_id: 'sp-aditi-001',
    skill_id: 's-cs-03',
    skill_name: 'Node.js',
    category: 'Backend Development',
    proficiency_score: 72,
    verification_status: 'INSTITUTION_VERIFIED',
    verified_by: 'RUAS Computer Science Dept',
    confidence_score: 80,
    updated_at: '2026-01-20T09:15:00Z',
  },
  {
    id: 'us-04',
    student_id: 'sp-aditi-001',
    skill_id: 's-cs-04',
    skill_name: 'SQL',
    category: 'Databases',
    proficiency_score: 48,
    verification_status: 'SELF_DECLARED',
    confidence_score: 65,
    updated_at: '2026-02-14T16:45:00Z',
  },
  {
    id: 'us-05',
    student_id: 'sp-aditi-001',
    skill_id: 's-cs-05',
    skill_name: 'Data Structures & Algorithms',
    category: 'Core Competency',
    proficiency_score: 61,
    verification_status: 'INSTITUTION_VERIFIED',
    verified_by: 'Prof. Ananya Sen',
    confidence_score: 75,
    updated_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'us-06',
    student_id: 'sp-aditi-001',
    skill_id: 's-gen-01',
    skill_name: 'Communication',
    category: 'Soft Skills',
    proficiency_score: 88,
    verification_status: 'INSTITUTION_VERIFIED',
    verified_by: 'RUAS Academic Council',
    confidence_score: 90,
    updated_at: '2026-01-20T09:15:00Z',
  },
  {
    id: 'us-04',
    student_id: 'sp-aditi-001',
    skill_id: 's02',
    skill_name: 'Research Methodology',
    category: 'Clinical',
    proficiency_score: 78,
    verification_status: 'INSTITUTION_VERIFIED',
    verified_by: 'Prof. Ananya Sen (AIIA)',
    confidence_score: 85,
    updated_at: '2026-02-01T16:00:00Z',
  },
  {
    id: 'us-05',
    student_id: 'sp-aditi-001',
    skill_id: 's12',
    skill_name: 'Scientific Writing',
    category: 'Communication',
    proficiency_score: 71,
    verification_status: 'SELF_DECLARED',
    confidence_score: 80,
    updated_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'us-06',
    student_id: 'sp-aditi-001',
    skill_id: 's15',
    skill_name: 'Data Analysis',
    category: 'Data & Analytics',
    proficiency_score: 48,
    verification_status: 'SELF_DECLARED',
    confidence_score: 70,
    updated_at: '2026-02-08T12:00:00Z',
  },
];

// Multi-Domain Assessment Questions Pool
export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  // 1. AYUSH & CLINICAL RESEARCH
  {
    id: 'q01',
    assessment_id: 'assm-ayush-01',
    skill_id: 's01',
    skill_name: 'Clinical Research',
    department: 'Ayurvedic Medicine & Surgery (AYUSH)',
    question_text: 'In randomized controlled trials (RCTs) for Ayurvedic herbal formulations, what is the primary purpose of double-blinding?',
    options: [
      'To reduce patient dropout rates during trial follow-up',
      'To prevent performance and detection bias from researchers and patients',
      'To accelerate regulatory approval from CDSCO',
      'To lower the total financial cost of the clinical study'
    ],
    correct_option_index: 1,
    difficulty_level: 'INTERMEDIATE',
    weight: 10,
  },
  {
    id: 'q02',
    assessment_id: 'assm-ayush-01',
    skill_id: 's03',
    skill_name: 'Ayurvedic Pharmacology',
    department: 'Ayurvedic Medicine & Surgery (AYUSH)',
    question_text: 'Which analytical technique is standardly employed for fingerprinting active marker compounds in herbal extract standardization?',
    options: [
      'High-Performance Thin-Layer Chromatography (HPTLC)',
      'Simple paper chromatography',
      'Bright-field optical microscopy',
      'Flame photometry'
    ],
    correct_option_index: 0,
    difficulty_level: 'ADVANCED',
    weight: 10,
  },

  // 2. COMPUTER SCIENCE & SOFTWARE ENGINEERING
  {
    id: 'q-cs-01',
    assessment_id: 'assm-cs-01',
    skill_id: 's-cs-01',
    skill_name: 'Python',
    department: 'Computer Science & Engineering',
    question_text: 'In Python, what is the time complexity of looking up a key in a built-in dictionary on average?',
    options: ['O(n)', 'O(1)', 'O(log n)', 'O(n log n)'],
    correct_option_index: 1,
    difficulty_level: 'BEGINNER',
    weight: 10,
  },
  {
    id: 'q-cs-02',
    assessment_id: 'assm-cs-01',
    skill_id: 's-cs-02',
    skill_name: 'React',
    department: 'Computer Science & Engineering',
    question_text: 'Which hook should be used to perform side effects in functional React components after DOM updates?',
    options: ['useMemo', 'useState', 'useEffect', 'useCallback'],
    correct_option_index: 2,
    difficulty_level: 'BEGINNER',
    weight: 10,
  },
  {
    id: 'q-cs-03',
    assessment_id: 'assm-cs-01',
    skill_id: 's-cs-03',
    skill_name: 'SQL',
    department: 'Computer Science & Engineering',
    question_text: 'Which SQL clause is used to filter records resulting from an aggregate GROUP BY query?',
    options: ['WHERE', 'HAVING', 'ORDER BY', 'JOIN'],
    correct_option_index: 1,
    difficulty_level: 'INTERMEDIATE',
    weight: 10,
  },

  // 3. MECHANICAL ENGINEERING
  {
    id: 'q-mech-01',
    assessment_id: 'assm-mech-01',
    skill_id: 's-mech-01',
    skill_name: 'SolidWorks',
    department: 'Mechanical Engineering',
    question_text: 'In SolidWorks 3D CAD design, what does the "Extrude Boss/Base" feature do?',
    options: [
      'Hollows out a solid body with specified wall thickness',
      'Extrudes a 2D closed sketch profile into a 3D solid geometry',
      'Applies a radius along an interior sharp edge',
      'Performs finite element stress analysis'
    ],
    correct_option_index: 1,
    difficulty_level: 'BEGINNER',
    weight: 10,
  },
  {
    id: 'q-mech-02',
    assessment_id: 'assm-mech-01',
    skill_id: 's-mech-03',
    skill_name: 'Thermodynamics',
    department: 'Mechanical Engineering',
    question_text: 'Which law of thermodynamics states that entropy of an isolated system always increases over time in a spontaneous process?',
    options: ['Zeroth Law', 'First Law', 'Second Law', 'Third Law'],
    correct_option_index: 2,
    difficulty_level: 'INTERMEDIATE',
    weight: 10,
  },

  // 4. COMMERCE & FINANCE
  {
    id: 'q-comm-01',
    assessment_id: 'assm-comm-01',
    skill_id: 's-comm-01',
    skill_name: 'Financial Analysis',
    department: 'Accounting & Finance',
    question_text: 'Which financial ratio measures a company\'s ability to pay off short-term obligations with its most liquid assets?',
    options: ['Quick Ratio (Acid-Test Ratio)', 'Debt-to-Equity Ratio', 'Return on Equity (ROE)', 'Gross Margin Ratio'],
    correct_option_index: 0,
    difficulty_level: 'INTERMEDIATE',
    weight: 10,
  },
  {
    id: 'q-comm-02',
    assessment_id: 'assm-comm-01',
    skill_id: 's-comm-04',
    skill_name: 'Advanced Excel',
    department: 'Accounting & Finance',
    question_text: 'Which modern Excel function replaces VLOOKUP and INDEX/MATCH for bidirectional matrix lookups?',
    options: ['XLOOKUP', 'HLOOKUP', 'SUMIF', 'COUNTIF'],
    correct_option_index: 0,
    difficulty_level: 'BEGINNER',
    weight: 10,
  },

  // 5. LAW & LEGAL STUDIES
  {
    id: 'q-law-01',
    assessment_id: 'assm-law-01',
    skill_id: 's-law-01',
    skill_name: 'Legal Research',
    department: 'Corporate & Cyber Law',
    question_text: 'What does the legal principle of "Stare Decisis" require in common law jurisdictions?',
    options: [
      'Courts must follow binding precedents set by higher courts in earlier cases',
      'Every law must be re-voted annually by parliament',
      'Contracts must be written in Latin to be legally enforceable',
      'Judges must issue rulings within 30 days of filing'
    ],
    correct_option_index: 0,
    difficulty_level: 'INTERMEDIATE',
    weight: 10,
  },

  // 6. PSYCHOLOGY
  {
    id: 'q-arts-01',
    assessment_id: 'assm-arts-01',
    skill_id: 's-arts-01',
    skill_name: 'Research Methodology',
    department: 'Psychology & Behavioral Sciences',
    question_text: 'What measure of internal consistency reliability is most commonly reported for psychological survey scales?',
    options: ['Cronbach\'s Alpha (α)', 'Pearson\'s r', 'Cohen\'s d', 'ANOVA F-statistic'],
    correct_option_index: 0,
    difficulty_level: 'INTERMEDIATE',
    weight: 10,
  },
];

// Multi-Domain Industry Opportunities Seed Data
export const OPPORTUNITIES_DATA: Opportunity[] = [
  // 1. COMPUTER SCIENCE & IT
  {
    id: 'opp-tech-01',
    industry_id: 'ind-google-01',
    company_name: 'Google India Cloud R&D',
    logo_url: '/logos/google.png',
    title: 'Software Engineering & Data Analytics Intern',
    description: 'Work with cloud engineering teams building scalable API endpoints, analyzing large-scale dataset telemetry, and writing python microservices.',
    opportunity_type: 'INTERNSHIP',
    location: 'Bengaluru / Hyderabad / Remote',
    is_remote: true,
    duration_months: 6,
    stipend_amount: 50000,
    deadline: '2027-12-31T23:59:59Z',
    eligibility_criteria: {
      min_cgpa: 7.5,
      allowed_streams: ['Engineering & Technology', 'Science & Mathematics', 'Commerce, Finance & Management'],
      allowed_years: [2, 3, 4],
    },
    status: 'ACTIVE',
    required_skills: [
      { skill_id: 's-cs-01', skill_name: 'Python', min_proficiency: 75, is_required: true },
      { skill_id: 's-cs-03', skill_name: 'SQL', min_proficiency: 70, is_required: true },
      { skill_id: 's-cs-02', skill_name: 'React', min_proficiency: 65, is_required: false },
      { skill_id: 's-cs-05', skill_name: 'Machine Learning', min_proficiency: 65, is_required: false },
    ],
    created_at: '2026-02-15T09:00:00Z',
  },

  // 2. MECHANICAL ENGINEERING
  {
    id: 'opp-mech-01',
    industry_id: 'ind-tata-01',
    company_name: 'Tata Motors Engineering Center',
    logo_url: '/logos/tata.png',
    title: 'Mechanical Design & CAD Engineer Intern',
    description: 'Design Automotive chassis components using SolidWorks and AutoCAD, run FEA stress simulations, and collaborate with manufacturing teams.',
    opportunity_type: 'INTERNSHIP',
    location: 'Pune, Maharashtra',
    is_remote: false,
    duration_months: 6,
    stipend_amount: 35000,
    deadline: '2027-12-31T23:59:59Z',
    eligibility_criteria: {
      min_cgpa: 7.0,
      allowed_streams: ['Engineering & Technology'],
      allowed_years: [3, 4],
    },
    status: 'ACTIVE',
    required_skills: [
      { skill_id: 's-mech-01', skill_name: 'SolidWorks', min_proficiency: 75, is_required: true },
      { skill_id: 's-mech-02', skill_name: 'AutoCAD', min_proficiency: 70, is_required: true },
      { skill_id: 's-mech-04', skill_name: 'Mechanical Design', min_proficiency: 70, is_required: true },
    ],
    created_at: '2026-02-12T10:00:00Z',
  },

  // 3. COMMERCE & FINANCE
  {
    id: 'opp-fin-01',
    industry_id: 'ind-pwc-01',
    company_name: 'PwC India Advisory',
    logo_url: '/logos/pwc.png',
    title: 'Financial Analyst & Audit Trainee',
    description: 'Perform financial modeling, statement audit reviews, and corporate valuation analysis for enterprise client portfolios.',
    opportunity_type: 'JOB',
    location: 'Mumbai / Gurugram',
    is_remote: false,
    duration_months: 12,
    stipend_amount: 45000,
    deadline: '2027-12-31T23:59:59Z',
    eligibility_criteria: {
      min_cgpa: 7.0,
      allowed_streams: ['Commerce, Finance & Management', 'Science & Mathematics'],
      allowed_years: [3, 4],
    },
    status: 'ACTIVE',
    required_skills: [
      { skill_id: 's-comm-01', skill_name: 'Financial Analysis', min_proficiency: 75, is_required: true },
      { skill_id: 's-comm-02', skill_name: 'Accounting', min_proficiency: 75, is_required: true },
      { skill_id: 's-comm-04', skill_name: 'Advanced Excel', min_proficiency: 80, is_required: true },
    ],
    created_at: '2026-02-14T11:00:00Z',
  },

  // 4. CORPORATE LAW
  {
    id: 'opp-law-01',
    industry_id: 'ind-cyril-01',
    company_name: 'Cyril Amarchand Mangaldas',
    logo_url: '/logos/law.png',
    title: 'Corporate Legal Research Intern',
    description: 'Conduct legal research on cross-border corporate compliance, draft commercial contracts, and prepare due diligence reports.',
    opportunity_type: 'INTERNSHIP',
    location: 'New Delhi / Mumbai',
    is_remote: false,
    duration_months: 3,
    stipend_amount: 30000,
    deadline: '2027-12-31T23:59:59Z',
    eligibility_criteria: {
      min_cgpa: 7.5,
      allowed_streams: ['Law & Legal Studies'],
      allowed_years: [3, 4, 5],
    },
    status: 'ACTIVE',
    required_skills: [
      { skill_id: 's-law-01', skill_name: 'Legal Research', min_proficiency: 75, is_required: true },
      { skill_id: 's-law-02', skill_name: 'Contract Drafting', min_proficiency: 70, is_required: true },
      { skill_id: 's-law-03', skill_name: 'Corporate Compliance', min_proficiency: 70, is_required: true },
    ],
    created_at: '2026-02-10T14:00:00Z',
  },

  // 5. AYUSH & HEALTHCARE RESEARCH
  {
    id: 'opp-dabur-01',
    industry_id: 'ind-dabur-01',
    company_name: 'Dabur Ayurvet R&D Division',
    logo_url: '/logos/dabur.png',
    title: 'Clinical Research Associate Intern',
    description: 'Work alongside senior scientific officers in standardizing AYUSH formulations, designing clinical trial case report forms (CRF), and performing bioactivity analysis.',
    opportunity_type: 'INTERNSHIP',
    location: 'New Delhi / Greater Noida',
    is_remote: false,
    duration_months: 6,
    stipend_amount: 25000,
    deadline: '2027-12-31T23:59:59Z',
    eligibility_criteria: {
      min_cgpa: 7.5,
      allowed_streams: ['Medical, AYUSH & Healthcare', 'Science & Mathematics'],
      allowed_years: [3, 4, 5],
    },
    status: 'ACTIVE',
    required_skills: [
      { skill_id: 's01', skill_name: 'Clinical Research', min_proficiency: 75, is_required: true },
      { skill_id: 's03', skill_name: 'Ayurvedic Pharmacology', min_proficiency: 80, is_required: true },
      { skill_id: 's02', skill_name: 'Research Methodology', min_proficiency: 70, is_required: true },
    ],
    created_at: '2026-02-01T09:00:00Z',
  },

  // 6. PSYCHOLOGY & BEHAVIORAL RESEARCH
  {
    id: 'opp-psych-01',
    industry_id: 'ind-mind-01',
    company_name: 'NIMHANS Behavioral Labs',
    logo_url: '/logos/nimhans.png',
    title: 'Psychology Research & Behavioral Intern',
    description: 'Design psychometric survey instruments, assist in cognitive testing experiments, and perform SPSS statistical analysis for mental health research.',
    opportunity_type: 'INTERNSHIP',
    location: 'Bengaluru / Remote',
    is_remote: true,
    duration_months: 6,
    stipend_amount: 28000,
    deadline: '2026-04-10T23:59:59Z',
    eligibility_criteria: {
      min_cgpa: 7.0,
      allowed_streams: ['Arts, Humanities & Social Sciences', 'Medical, AYUSH & Healthcare'],
      allowed_years: [2, 3, 4],
    },
    status: 'ACTIVE',
    required_skills: [
      { skill_id: 's-arts-01', skill_name: 'Research Methodology', min_proficiency: 70, is_required: true },
      { skill_id: 's-arts-02', skill_name: 'Psychometrics', min_proficiency: 70, is_required: true },
      { skill_id: 's-stat-01', skill_name: 'Statistics', min_proficiency: 65, is_required: true },
    ],
    created_at: '2026-02-16T12:00:00Z',
  },
];

// Initial Applications Seed Data
export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-01',
    opportunity_id: 'opp-dabur-01',
    student_id: 'sp-aditi-001',
    student_name: 'Aditi Sharma',
    opportunity_title: 'Clinical Research Associate Intern',
    company_name: 'Dabur Ayurvet R&D Division',
    status: 'SHORTLISTED',
    match_score: 94,
    match_breakdown: {
      overallScore: 94,
      skillScore: 96,
      interestScore: 100,
      educationScore: 100,
      projectScore: 91,
      certificationScore: 88,
      experienceScore: 82,
      locationScore: 90,
      matchedSkills: [
        { skillName: 'Clinical Research', studentScore: 86, requiredScore: 75 },
        { skillName: 'Ayurvedic Pharmacology', studentScore: 92, requiredScore: 80 },
        { skillName: 'Research Methodology', studentScore: 78, requiredScore: 70 },
      ],
      missingSkills: [
        { skillName: 'Biostatistics', studentScore: 45, requiredScore: 65, gap: 20 },
      ],
      reasons: ['Strong alignment with target role', 'High proficiency in clinical research and pharmacology'],
    },
    applied_at: '2026-02-16T10:00:00Z',
    updated_at: '2026-02-18T15:30:00Z',
  },
];
